services:
  # node:
  #   image: node:20-alpine
  #   working_dir: /usr/src/app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app # sync your project files
  #     - /usr/src/app/node_modules # keep node_modules inside container
  #   command: sh -c "npm install && npm run dev"

  postgress:
    image: postgres:16-alpine
    container_name: my_postgres_container
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
